ALTER TABLE "Restaurant"
ADD COLUMN "taxRate" DECIMAL(5, 2) NOT NULL DEFAULT 10,
ADD COLUMN "taxIncluded" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'EUR',
ADD COLUMN "currencySymbol" TEXT NOT NULL DEFAULT '€',
ADD COLUMN "openingTime" TEXT NOT NULL DEFAULT '10:00',
ADD COLUMN "closingTime" TEXT NOT NULL DEFAULT '23:00',
ADD COLUMN "kitchenAlertMinutes" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "allowTakeaway" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "notificationSounds" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "ticketMessage" TEXT;
